@extends('pdf.layouts.document')
@php($money = fn ($value) => ($currency ?? 'C$') . ' ' . number_format((float) $value, 2))
@section('content')
    @section('document-heading')<div class="blue" style="font-size:15px; font-weight:bold;">PROFORMA DE PEDIDO</div>@endsection
    @section('document-meta')<div>Fecha<br><strong>{{ $dateFormatted ?? '—' }}</strong></div>@endsection
    @include('pdf.partials.company-header')
    @if($isDraft) <div style="border:1px solid #9aa8b1; color:#63717a; display:inline-block; padding:3px 7px; font-size:8px; letter-spacing:.5px;">BORRADOR</div> @endif
    <table style="margin-top:12px;" class="avoid-break"><tr><td style="width:55%; vertical-align:top;"><strong class="blue">{{ $company['nombre'] }}</strong><br>{{ $company['ruc'] ?? '' }}<br>{{ $company['direccion'] ?? '' }}<br>{{ $company['ciudad'] ?? '' }} {{ $company['pais'] ?? '' }}</td><td style="vertical-align:top;"><strong class="blue">CLIENTE</strong><br>{{ $proforma->nombre_cliente }}<br>{{ $proforma->ruc ?? '' }}<br>{{ $proforma->telefono ?? '' }} · {{ $proforma->correo ?? '' }}<br>{{ $proforma->direccion ?? '' }}</td></tr></table>
    <h2 class="section-title">Detalle</h2>
    <table class="pdf-table"><thead><tr style="background:#e9eef1; color:#123852;"><th style="padding:7px; text-align:left;">Cant.</th><th style="padding:7px; text-align:left;">Descripción</th><th style="padding:7px; text-align:right;">Precio unit.</th><th style="padding:7px; text-align:right;">Precio total</th></tr></thead><tbody>
        @foreach($details as $detail)<tr class="item-row"><td style="padding:7px; border-bottom:1px solid #d9e0e4;">{{ $detail['quantity'] }}</td><td style="padding:7px; border-bottom:1px solid #d9e0e4;"><strong>{{ $detail['name'] }}</strong>@if(!empty($detail['description']))<br><span class="muted">{{ $detail['description'] }}</span>@endif</td><td class="amount" style="padding:7px; border-bottom:1px solid #d9e0e4;">{{ $money($detail['unit_price']) }}</td><td class="amount" style="padding:7px; border-bottom:1px solid #d9e0e4;">{{ $money($detail['subtotal']) }}</td></tr>@foreach($detail['services'] as $service)<tr class="item-row"><td style="padding:4px 7px 4px 20px; border-bottom:1px solid #d9e0e4;">{{ $service['quantity'] }}</td><td style="padding:4px 7px; border-bottom:1px solid #d9e0e4;"><span class="muted">↳ {{ $service['name'] }}@if($service['detail']) · {{ $service['detail'] }} @endif</span></td><td class="amount" style="padding:4px 7px; border-bottom:1px solid #d9e0e4;">{{ $money($service['unit_price']) }}</td><td class="amount" style="padding:4px 7px; border-bottom:1px solid #d9e0e4;">{{ $money($service['subtotal']) }}</td></tr>@endforeach @endforeach
        @foreach($proforma->servicios as $service)<tr class="item-row"><td style="padding:7px; border-bottom:1px solid #d9e0e4;">{{ $service->cantidad }}</td><td style="padding:7px; border-bottom:1px solid #d9e0e4;"><strong>{{ $service->servicio_nombre_snapshot }}</strong>@if($service->detalle)<br><span class="muted">{{ $service->detalle }}</span>@endif</td><td class="amount" style="padding:7px; border-bottom:1px solid #d9e0e4;">{{ $money($service->precio_unitario) }}</td><td class="amount" style="padding:7px; border-bottom:1px solid #d9e0e4;">{{ $money($service->subtotal) }}</td></tr>@endforeach
    </tbody></table>
    <table class="totals"><tr><td>Subtotal</td><td class="amount">{{ $money($proforma->subtotal_bruto) }}</td></tr>@if((float)$proforma->descuento_total)<tr><td>Descuento</td><td class="amount">- {{ $money($proforma->descuento_total) }}</td></tr>@endif @if((float)$proforma->monto_iva)<tr><td>IVA</td><td class="amount">{{ $money($proforma->monto_iva) }}</td></tr>@endif @if((float)$proforma->monto_ir)<tr><td>IR</td><td class="amount">- {{ $money(abs($proforma->monto_ir)) }}</td></tr>@endif<tr class="total-row"><td>TOTAL</td><td class="amount">{{ $money($proforma->total) }}</td></tr></table>
    @if($proforma->valida_hasta || $paymentConditions || $proforma->observaciones)<h2 class="section-title">Condiciones y observaciones</h2><div class="avoid-break">@if($proforma->valida_hasta)<p>Esta proforma es válida hasta el {{ $proforma->valida_hasta->format('d/m/Y') }}.</p>@endif @if($paymentConditions)<p>{{ $paymentConditions }}</p>@endif @if($proforma->observaciones)<p><strong>Observaciones:</strong> {{ $proforma->observaciones }}</p>@endif</div>@endif
    @include('pdf.partials.footer')
    @foreach($sheets as $sheet)<div class="page-break">@include('pdf.proforma.product-sheet', ['sheet' => $sheet])</div>@endforeach
@endsection
