@extends('pdf.layouts.document')
@php($money = fn ($value) => ($currency ?? 'C$') . ' ' . number_format((float) $value, 2))
@section('content')
    @section('document-heading')<div class="blue" style="font-size:16px; font-weight:bold;">FACTURA</div>@endsection
    @section('document-meta')<div>Número<br><strong>{{ $factura->numero }}</strong><br><br>Fecha<br><strong>{{ $dateFormatted ?? '—' }}</strong></div>@endsection
    @include('pdf.partials.company-header')
    <table class="avoid-break" style="margin-bottom:20px;"><tr><td style="width:50%; vertical-align:top;"><strong class="blue">EMISOR</strong><br>{{ $company['nombre'] }}<br>{{ $company['ruc'] ?? '' }}<br>{{ $company['direccion'] ?? '' }}<br>{{ $company['telefono'] ?? '' }} · {{ $company['correo'] ?? '' }}</td><td style="vertical-align:top;"><strong class="blue">CLIENTE</strong><br>{{ $factura->nombre_cliente }}<br>{{ $factura->ruc ?? '' }}<br>{{ $factura->direccion ?? '' }}<br>{{ $factura->telefono ?? '' }} · {{ $factura->correo ?? '' }}</td></tr></table>
    <table class="small avoid-break" style="border-top:1px solid #ccd4d9; border-bottom:1px solid #ccd4d9; padding:7px 0; margin-bottom:20px;"><tr><td><strong>Vendedor:</strong> {{ $factura->usuario?->nombre ?? '—' }}</td><td><strong>Canal:</strong> {{ $factura->canal ?? '—' }}</td><td><strong>Método:</strong> {{ $factura->metodo_pago ?? '—' }}</td><td><strong>Origen:</strong> {{ $factura->origen === 'pedido' ? 'Pedido ' . ($factura->pedido?->numero ?? '') : 'Venta directa' }}</td></tr></table>
    <table class="pdf-table"><thead><tr style="border-bottom:2px solid #123852; color:#123852;"><th style="padding:7px; text-align:left;">Cant.</th><th style="padding:7px; text-align:left;">Descripción</th><th style="padding:7px; text-align:right;">Precio unit.</th><th style="padding:7px; text-align:right;">Descuento</th><th style="padding:7px; text-align:right;">Subtotal</th></tr></thead><tbody>
    @foreach($details as $detail)<tr class="item-row"><td style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $detail['quantity'] }}</td><td style="padding:7px; border-bottom:1px solid #e1e6e9;"><strong>{{ $detail['name'] }}</strong>@if($detail['description'])<br><span class="muted">{{ $detail['description'] }}</span>@endif @if($detail['colors'])<br><span class="muted small">{{ implode(' / ', $detail['colors']) }}</span>@endif</td><td class="amount" style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $money($detail['unit_price']) }}</td><td class="amount" style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $money($detail['discount']) }}</td><td class="amount" style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $money($detail['subtotal']) }}</td></tr>@foreach($detail['services'] as $service)<tr class="item-row"><td style="padding:4px 7px 4px 20px; border-bottom:1px solid #e1e6e9;">{{ $service['quantity'] }}</td><td style="padding:4px 7px; border-bottom:1px solid #e1e6e9;"><span class="muted">↳ {{ $service['name'] }} @if($service['detail']) · {{ $service['detail'] }} @endif</span></td><td class="amount" style="padding:4px 7px; border-bottom:1px solid #e1e6e9;">{{ $money($service['unit_price']) }}</td><td class="amount" style="padding:4px 7px; border-bottom:1px solid #e1e6e9;">{{ $money($service['discount']) }}</td><td class="amount" style="padding:4px 7px; border-bottom:1px solid #e1e6e9;">{{ $money($service['subtotal']) }}</td></tr>@endforeach @endforeach
    @foreach($services as $service)<tr class="item-row"><td style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $service['quantity'] }}</td><td style="padding:7px; border-bottom:1px solid #e1e6e9;"><strong>{{ $service['name'] }}</strong>@if($service['detail'])<br><span class="muted">{{ $service['detail'] }}</span>@endif</td><td class="amount" style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $money($service['unit_price']) }}</td><td class="amount" style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $money($service['discount']) }}</td><td class="amount" style="padding:7px; border-bottom:1px solid #e1e6e9;">{{ $money($service['subtotal']) }}</td></tr>@endforeach
    </tbody></table>
    <table class="totals"><tr><td>Subtotal</td><td class="amount">{{ $money($factura->subtotal) }}</td></tr>@if((float)$factura->descuento)<tr><td>Descuento</td><td class="amount">- {{ $money($factura->descuento) }}</td></tr>@endif @if((float)$factura->monto_iva)<tr><td>IVA</td><td class="amount">{{ $money($factura->monto_iva) }}</td></tr>@endif @if((float)$factura->monto_ir)<tr><td>IR</td><td class="amount">- {{ $money(abs($factura->monto_ir)) }}</td></tr>@endif<tr class="total-row"><td>TOTAL</td><td class="amount">{{ $money($factura->total) }}</td></tr></table>
    <div class="footer">Gracias por su compra.<br><strong>Autorizado por</strong><br>@if(!empty($company['firma'])) <img src="{{ $company['firma'] }}" style="max-width:120px; max-height:45px; margin-top:8px;"> @endif @if(!empty($company['sello'])) <img src="{{ $company['sello'] }}" style="max-width:70px; max-height:45px; margin:8px 0 0 20px;"> @endif</div>
@endsection
